[package]
name = "hamr_readfile_range_many"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rust_am_lib = { workspace = true }
serde_stacker = "0.1"
flate2 = "1.0"
